name: Build and Package Neon Copper Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Cache Maven Dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # Step 4: Build with Maven
      - name: Build project with Maven
        run: mvn clean package -DskipTests

      # Step 5: Upload Compiled JAR as Artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: copper-plugins
          path: target/*.jar
